parameters:
    digitalocean.class:      Thanatos\DigitalOceanBundle\Service\DigitalOceanService

services:
    digitalocean:
        class:        "%digitalocean.class%"
        arguments:    [%digitalocean.clientid%, %digitalocean.apikey%]
